graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hackernews
  profiles:
    active: local

server:
  port: 8080

graphiql:
  enabled: true
  headers:
    Authorization: sample-key