graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  profiles:
    active: local

server:
  port: 8080

